apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/canary":"true","nginx.ingress.kubernetes.io/canary-weight":"5"},"name":"demo-canary","namespace":"canary"},"spec":{"ingressClassName":"nginx","rules":[{"host":"demo.local","http":{"paths":[{"backend":{"service":{"name":"demo-v2","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "5"
  creationTimestamp: "2025-10-16T23:28:37Z"
  generation: 1
  name: demo-canary
  namespace: canary
  resourceVersion: "1919"
  uid: dcfbfa2e-a501-4a8e-84d6-fcbb48317aa7
spec:
  ingressClassName: nginx
  rules:
  - host: demo.local
    http:
      paths:
      - backend:
          service:
            name: demo-v2
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 192.168.49.2
