apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx"},"name":"demo-base","namespace":"canary"},"spec":{"ingressClassName":"nginx","rules":[{"host":"demo.local","http":{"paths":[{"backend":{"service":{"name":"demo-v1","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: nginx
  creationTimestamp: "2025-10-16T23:28:37Z"
  generation: 1
  name: demo-base
  namespace: canary
  resourceVersion: "1920"
  uid: 16dfce89-7b67-4914-b19f-b09f6aa1e1e9
spec:
  ingressClassName: nginx
  rules:
  - host: demo.local
    http:
      paths:
      - backend:
          service:
            name: demo-v1
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 192.168.49.2
